/**
 * GenerationSnapshot BEHAVIORAL round-trip tests (C5 — the first behavior-first brick).
 *
 * Unlike the sibling `generationSnapshotModel.test.ts` (which is `validateSync()`, shape-only,
 * no DB), these tests WRITE a real document to an in-memory mongod and READ IT BACK. A
 * `validateSync()` over a healthy golden CANNOT catch a strict-mode field-strip, because the
 * strip happens at `.create()`/insert time, not at validation time. That gap is exactly what
 * hid the two confirmed data-loss defects these tests pin (m5-cutover.md §J):
 *
 *   D-1  Python emits `diagnostics.engineFailure` on every §D failure/degenerate write
 *        (snapshot.py). The Mongoose `diagnostics` sub-schema had no such field + default
 *        `strict:true`, so it was silently stripped on insert — the entire §D failure corpus
 *        (the reason the degenerate arm exists) would be lost.
 *   D-2  Python emits top-level `controls` on EVERY write (snapshot.py, §G.1 F6). The root
 *        schema had no `controls` field → stripped → the R9 regen-controls learning signal
 *        lost from every snapshot.
 *
 * Reference: docs/plans/m5-cutover.md §G items 4/5 + §J; snapshot.py EngineFailure / _controls_dict.
 */
import fs from "fs";
import path from "path";
import { Types } from "mongoose";
import GenerationSnapshot, {
  ENGINE_FAILURE_STAGES,
  ENGINE_FAILURE_CODES,
  type GenerationSnapshotDocument,
} from "@/models/GenerationSnapshot";
import { startMemoryMongo, type MongoHarness } from "./helpers/mongoHarness";

// The committed cross-runtime e2e fixture — the exact Python-produced wire doc the C5 writer
// persists (regenerated by the ml-system e2e test). The single source that both runtimes target.
const FIXTURE = path.join(__dirname, "../../ml-system/tests/fixtures/m4b_e2e_snapshot.json");
const loadFixture = () => JSON.parse(fs.readFileSync(FIXTURE, "utf8")) as Record<string, unknown>;
// The TS/M5-supplied fields the Python producer half does not author (mirrors m4bSnapshotContract).
const withM5Merge = (wire: Record<string, unknown>) => ({
  ...wire,
  user: new Types.ObjectId(),
  interactionCountAtRequest: 0,
});

let harness: MongoHarness;

beforeAll(async () => {
  harness = await startMemoryMongo([GenerationSnapshot]);
}, 120_000); // first run may download the mongod binary

afterAll(async () => {
  await harness.stop();
});

afterEach(async () => {
  await harness.clear();
});

const oid = () => new Types.ObjectId();

/** A minimal valid snapshot (mirrors generationSnapshotModel.test.ts validBase). */
const validBase = () => ({
  user: oid(),
  sessionId: "user-1",
  candidateCacheKey: "ck-1",
  generationIndex: 0,
  intent: "daily",
  occasion: "casual",
  weather: "mild",
  wardrobeVersion: 0,
  interactionCountAtRequest: 0,
  fittedCoreVersion: "0.4.0",
  generator: {
    provider: "openai",
    model: "gpt-5.4-mini",
    temperature: 0.5,
    promptVersion: "m5-c1.v1",
    // §G item 6 — required provenance the service authors on every write.
    maxCompletionTokens: 2200,
    apiSurface: "chat_completions",
    responseFormat: "json_schema_strict",
    reasoningEffort: "none",
    storeMode: "none",
    promptCacheRetention: "in_memory",
    timeoutSeconds: 30,
    maxRetries: 0,
  },
  rankerConfigVersion: "deadbeef",
  scorer: { kind: "cold_start", available: true },
  itemSnapshots: [],
  generationAttempts: [],
  candidates: [],
  shownCandidateIds: [],
  shownFullSignatures: [],
  nSurfaced: 0,
  spreadCollapsed: false,
});

// ---------------------------------------------------------------------------
// Meta: prove the harness round-trips at all (a green here isolates D-1/D-2 failures
// to the schema, not the DB wiring).
// ---------------------------------------------------------------------------
describe("harness sanity", () => {
  it("writes and reads back a minimal snapshot", async () => {
    const created = await GenerationSnapshot.create(validBase());
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();
    expect(readBack).not.toBeNull();
    expect(readBack!.intent).toBe("daily");
  });
});

// ---------------------------------------------------------------------------
// D-1 — diagnostics.engineFailure must survive a real write→read (not be strict-stripped).
// ---------------------------------------------------------------------------
describe("D-1 diagnostics.engineFailure round-trip", () => {
  it("a degenerate snapshot persists engineFailure and reads it back non-null", async () => {
    const doc = {
      ...validBase(),
      diagnostics: {
        notEnoughItems: false,
        parse: { parseSuccess: false, repairUsed: true, generatorCalls: 1 },
        // The §D wire shape the service emits (snapshot.py EngineFailure.to_payload_dict,
        // camelCased by snapshot_serde):
        engineFailure: {
          stage: "parse",
          code: "parse_fail",
          message: "GPT output failed JSON repair",
          messageTruncated: false,
          detail: { itemId: oid().toHexString(), count: 3 },
        },
      },
    };

    const created = await GenerationSnapshot.create(doc);
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();

    // The load-bearing assertion: the failure corpus survives the insert.
    expect(readBack!.diagnostics?.engineFailure).toBeTruthy();
    expect(readBack!.diagnostics?.engineFailure?.stage).toBe("parse");
    expect(readBack!.diagnostics?.engineFailure?.code).toBe("parse_fail");
    expect(readBack!.diagnostics?.engineFailure?.message).toBe("GPT output failed JSON repair");
    expect(readBack!.diagnostics?.engineFailure?.messageTruncated).toBe(false);
    expect(readBack!.diagnostics?.engineFailure?.detail?.count).toBe(3);
  });

  it("closed vocab mirrors the Python EngineFailure sets", () => {
    // A rename on either side silently empties the degenerate corpus mapping — pin the mirror.
    expect(ENGINE_FAILURE_STAGES).toEqual(
      new Set(["sample", "generate", "parse", "validate", "rank", "assemble", "pre_generation", "unknown"]),
    );
    expect(ENGINE_FAILURE_CODES).toEqual(
      new Set([
        "parse_fail",
        "empty_valid_set",
        "refusal",
        "truncated",
        "internal_exception",
        "sampler_error",
        "ranker_error",
        "unknown",
      ]),
    );
  });

  it("rejects an out-of-set engineFailure stage/code on write", async () => {
    const bad = {
      ...validBase(),
      diagnostics: {
        engineFailure: { stage: "teleport", code: "parse_fail", message: "x" },
      },
    };
    await expect(GenerationSnapshot.create(bad)).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
// D-2 — top-level controls must survive a real write→read.
// ---------------------------------------------------------------------------
describe("D-2 top-level controls round-trip", () => {
  it("a render with populated controls reads them back", async () => {
    const lockedItemIds = [oid().toHexString(), oid().toHexString()];
    const dislikedItemIds = [oid().toHexString()];
    const created = await GenerationSnapshot.create({
      ...validBase(),
      controls: { lockedItemIds, dislikedItemIds },
    });
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();

    expect(readBack!.controls).toBeTruthy();
    expect(readBack!.controls?.lockedItemIds).toEqual(lockedItemIds);
    expect(readBack!.controls?.dislikedItemIds).toEqual(dislikedItemIds);
  });

  it("controls is present (empty arrays) on a first render that supplies none — never absent", async () => {
    // §G.1 F6: "no controls" is an explicit corpus statement, not a stripped/absent subdoc.
    const created = await GenerationSnapshot.create(validBase());
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();

    expect(readBack!.controls).toBeTruthy();
    expect(readBack!.controls?.lockedItemIds).toEqual([]);
    expect(readBack!.controls?.dislikedItemIds).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Item-6 generator provenance + finishStatus — the SAME silent-strip class as D-1/D-2
// (m5-cutover.md §G item 6). Guarded here so a re-introduced strip reddens the suite instead
// of silently dropping provenance M6 stratifies by.
// ---------------------------------------------------------------------------
describe("generator provenance round-trip (§G item 6)", () => {
  it("every generator provenance field of the committed fixture survives a real write→read", async () => {
    const wire = loadFixture();
    const created = await GenerationSnapshot.create(withM5Merge(wire));
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();

    // The load-bearing assertion: the WHOLE block round-trips, not just the four M4 base fields.
    // .toEqual against the fixture's own generator catches any single stripped/renamed subfield.
    expect(readBack!.generator).toMatchObject(wire.generator as Record<string, unknown>);
    // Spot the item-6 additions explicitly (a strip would leave these undefined):
    expect(readBack!.generator.maxCompletionTokens).toBe(2200);
    expect(readBack!.generator.apiSurface).toBe("chat_completions");
    expect(readBack!.generator.responseFormat).toBe("json_schema_strict");
    expect(readBack!.generator.reasoningEffort).toBe("none");
    expect(readBack!.generator.storeMode).toBe("none");
    expect(readBack!.generator.promptCacheRetention).toBe("in_memory");
    expect(readBack!.generator.timeoutSeconds).toBe(30);
    expect(readBack!.generator.maxRetries).toBe(0);
  });

  it("run-level generator.finishStatus survives on an abnormal (truncated) run", async () => {
    // snapshot.abnormal_finish_status → {finishReason, refused}.
    const created = await GenerationSnapshot.create({
      ...validBase(),
      generator: { ...validBase().generator, finishStatus: { finishReason: "length", refused: false } },
    });
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();
    expect(readBack!.generator.finishStatus?.finishReason).toBe("length");
    expect(readBack!.generator.finishStatus?.refused).toBe(false);
  });

  it("per-attempt generationAttempts[].finishStatus survives (paid-but-degenerate signal)", async () => {
    // snapshot._finish_status_dict → {finishReason, refusal}.
    const created = await GenerationSnapshot.create({
      ...validBase(),
      generationAttempts: [
        {
          attemptId: "a0",
          attemptIndex: 0,
          isRepair: false,
          payloadParsed: false,
          finishStatus: { finishReason: "length", refusal: "I can't help with that" },
        },
      ],
    });
    const readBack = await GenerationSnapshot.findById(created._id).lean<GenerationSnapshotDocument>();
    expect(readBack!.generationAttempts[0].finishStatus?.finishReason).toBe("length");
    expect(readBack!.generationAttempts[0].finishStatus?.refusal).toBe("I can't help with that");
  });
});
