/**
 * M4b C8 — cross-language contract proof.
 *
 * The Python side (ml-system/tests/test_m4_e2e_fixture.py) builds a real GenerationSnapshot wire
 * doc (build_snapshot_payload → snapshot_serde.to_wire) and freezes it as a committed fixture.
 * This test validates that EXACT Python-produced doc against the real C5 Mongoose model — proving
 * the data contract composes across the language boundary, which is what M5 inherits.
 *
 * The Python payload is only the producer half; M5 merges in the TS-owned fields (user, and the
 * interactionCountAtRequest Lens field) before insert. This test makes that merge concrete.
 *
 * Reference: docs/plans/m4-data-model-migration.md §14 (C8) + the M5-handoff note.
 */
import fs from "fs";
import path from "path";
import { Types } from "mongoose";
import GenerationSnapshot from "@/models/GenerationSnapshot";
import OutfitInteraction from "@/models/OutfitInteraction";

const FIXTURE = path.join(__dirname, "../../ml-system/tests/fixtures/m4b_e2e_snapshot.json");

type WireCandidate = {
  candidateId: string;
  baseKey: string;
  fullSignature: string;
  items: unknown[];
  shown: boolean;
};
type WireDoc = {
  itemSnapshots: { engineVisible: { clothingType: string } }[];
  generator: { promptVersion: string };
  scorer: { kind: string };
  diagnostics: { samplerPerType: Record<string, unknown> };
  candidates: WireCandidate[];
  shownCandidateIds: string[];
  shownFullSignatures: string[];
  [key: string]: unknown;
};

function loadWire(): WireDoc {
  return JSON.parse(fs.readFileSync(FIXTURE, "utf8")) as WireDoc;
}

// The TS/M5-supplied fields the Python producer half does not author.
function withM5Merge(wire: Record<string, unknown>) {
  return { ...wire, user: new Types.ObjectId(), interactionCountAtRequest: 0 };
}

describe("M4b C8 — the Python wire doc validates against the C5 schema", () => {
  it("the committed fixture exists (regenerated by the Python e2e test)", () => {
    expect(fs.existsSync(FIXTURE)).toBe(true);
  });

  it("a Python-produced snapshot + the M5 merge is a valid GenerationSnapshot", () => {
    const doc = new GenerationSnapshot(withM5Merge(loadWire()));
    const err = doc.validateSync();
    expect(err).toBeUndefined();
  });

  it("without the M5-merged fields the same doc is invalid (documents what M5 must supply)", () => {
    const err = new GenerationSnapshot(loadWire()).validateSync();
    // user + interactionCountAtRequest are required and Python does not author them.
    expect(err?.errors.user).toBeDefined();
    expect(err?.errors.interactionCountAtRequest).toBeDefined();
  });

  it("the wire doc preserves the engineVisible partition-key rename + provenance block", () => {
    const wire = loadWire();
    expect(wire.itemSnapshots[0].engineVisible.clothingType).toBeTruthy(); // type → clothingType
    expect(wire.generator.promptVersion).toBeTruthy();
    expect(wire.scorer.kind).toBe("cold_start");
    // the data-Map key crossed verbatim (the serde opaque-preservation, not "outerLayer").
    expect(wire.diagnostics.samplerPerType).toHaveProperty("outer_layer");
  });
});

describe("M4b C8 — the OutfitInteraction binding round-trips to the snapshot", () => {
  it("a {snapshotId, candidateId, baseKey, fullSignature} binding validates + is a shown candidate", async () => {
    const wire = loadWire();

    // M5 re-reads the candidate from the immutable snapshot and SERVER-SETS items/keys (never the
    // client echo). Here the snapshot is the fixture; the binding is built from a re-read candidate.
    const shownId: string = wire.shownCandidateIds[0];
    const candidate = wire.candidates.find((c: WireCandidate) => c.candidateId === shownId);
    if (!candidate) throw new Error(`shown candidate ${shownId} not found in the fixture`);

    const interaction = new OutfitInteraction({
      user: new Types.ObjectId(),
      items: candidate.items.map(() => new Types.ObjectId()), // server-set from the re-read candidate
      action: "accepted",
      snapshotId: new Types.ObjectId(),
      candidateId: candidate.candidateId,
      baseKey: candidate.baseKey,
      fullSignature: candidate.fullSignature,
    });

    // the co-presence guard accepts a fully-bound row...
    await expect(interaction.validate()).resolves.toBeUndefined();
    // ...membership: the bound candidate was actually shown, and its keys are the snapshot's.
    expect(wire.shownCandidateIds).toContain(candidate.candidateId);
    expect(wire.shownFullSignatures).toContain(candidate.fullSignature);
  });

  it("a partial binding (snapshotId without the re-read keys) is rejected by the co-presence guard", async () => {
    const wire = loadWire();
    const interaction = new OutfitInteraction({
      user: new Types.ObjectId(),
      items: [new Types.ObjectId()],
      action: "accepted",
      snapshotId: new Types.ObjectId(),
      candidateId: wire.shownCandidateIds[0],
      // baseKey / fullSignature omitted — a partial binding that would poison the projections.
    });
    await expect(interaction.validate()).rejects.toThrow(/all present or all absent/);
  });
});
